name: Create Docker container and push to dockerHub

on:
  workflow_call:
    inputs:
      dockerhub-tag:
        required: true
        type: string
      artifact-name:
        required: true
        type: string
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_PASSWORD:
        required: true
      DOCKERHUB_REPOSITORY:
        required: true

jobs:
  build-push-docker:
    name: Build and push Docker Container
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v3.0.0
        with:
          name: ${{ inputs.artifact-name }}

      - name: List current directory and "build" folder
        run: ls && echo "\nBuild folder:" && ls build
      
      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build Container image
        run: docker build -t ${{ secrets.DOCKERHUB_REPOSITORY }}:${{ inputs.dockerhub-tag }} . # Beachte den punkt am ende als Pfad

      - name: Publish Docker image
        run: docker push ${{ secrets.DOCKERHUB_REPOSITORY }}:${{ inputs.dockerhub-tag }}

      - name: Log out of Docker Hub
        run: docker logout
