name: Create Docker container and push to GitHub registry

on:
  workflow_call:
    inputs:
      container-tag:
        type: string
      artifact-name:
        required: true
        type: string
      artifact-path:
        type: string
        default: /target

jobs:
  build-push-docker:
    name: Build and push Docker Container
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v3.0.0
        with:
          name: ${{ inputs.artifact-name }}
          path: ${{ inputs.artifact-path }}

      - name: List current directory
        run: ls
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Container image
        if: inputs.container-tag != ''
        run: docker build -t ghcr.io/${GITHUB_REPOSITORY}:v${{ inputs.container-tag }} -t ghcr.io/${GITHUB_REPOSITORY}:latest ${{ inputs.artifact-path }} # Im Pfad am Ende muss das Dockerfile liegen

      - name: Build Container image
        if: inputs.container-tag == ''
        run: docker build -t ghcr.io/${GITHUB_REPOSITORY}:latest ${{ inputs.artifact-path }} # Im Pfad am Ende muss das Dockerfile liegen

      - name: Push image to DockerHub
        run: docker push ghcr.io/${GITHUB_REPOSITORY} --all-tags
