name: Create Docker container and push to dockerHub

on:
  workflow_call:
    inputs:
      container-tag:
        required: true
        type: string
      artifact-name:
        required: true
        type: string
      artifact-path:
        type: string
        default: /target

jobs:
  build-push-docker:
    name: Build and push Docker Container
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v3.0.0
        with:
          name: ${{ inputs.artifact-name }}
          path: ${{ inputs.artifact-path }}

      - name: List current directory
        run: ls
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Container image
        run: docker build -t ghcr.io/thb-it-oldenburg/${{ GITHUB_REPOSITORY }}:${{ inputs.container-tag }} -t ${{ secrets.DOCKERHUB_REPOSITORY }}:latest . # Beachte den punkt am ende als Pfad

      - name: Push image to DockerHub
        run: docker push ghcr.io/thb-it-oldenburg/${{ GITHUB_REPOSITORY }}:${{ inputs.container-tag }}

      - name: Log out of DockerHub
        run: docker logout
