on:
  workflow_call:
    inputs:
      build-profile:
        type: string
        default: preview
      auto-submit-profile:
        type: string
        default: preview
      platform:
        type: string
        default: android
      build-flags:
        type: string
        required: false
        description: Additional flags for the eas build command
        
    secrets:
      EXPO_TOKEN:
        required: true
        description: A token for expo.dev access via command line
      SERVICE_ACCOUNT_KEY_FILE_CONTENT:
        required: true
        description: The Google Service key Json File. # Note that quotation marks must be inserted with escape backslash like \" .
        # The echo command will break otherwise.

jobs:
  publish:
    name: Build and Publish to Google Console
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
      
      - name: change.env
        run: |
          rm .env
          echo -e "\nREACT_APP_GATEWAY_HOSTNAME=${{ vars.REACT_APP_GATEWAY_HOSTNAME }}\nREACT_APP_API_PROTOCOL=${{ vars.REACT_APP_API_PROTOCOL }}" >> .env
          cat .env
      
      - name: Setup serviceAccountKey.json
        run: |
          echo "${{ secrets.SERVICE_ACCOUNT_KEY_FILE_CONTENT }}" >> Service-Account-Key.json
          
      - name: Create .npmrc with environment variable for GHPR
        run: |
          echo -e "//npm.pkg.github.com/:_authToken=\${GH_PKG_TOKEN}\n@thb-it-oldenburg:registry=https://npm.pkg.github.com/" >> .npmrc
          cat .npmrc

      - name: Build and Push to Google-Console
        run: eas build --profile ${{ inputs.build-profile }} --platform ${{ inputs.platform }}  --auto-submit-with-profile ${{ inputs.auto-submit-profile }} --non-interactive ${{ inputs.build-flags }}
