on:
  workflow_call:
    inputs:
      build-profile:
        type: string
        default: preview
      auto-submit-profile:
        type: string
        default: preview
      platform:
        type: string
        default: android
      build-flags:
        type: string
        required: false
        description: Additional flags for the eas build command
        
    secrets:
      EXPO_TOKEN:
        required: true
        description: A token for expo.dev access via command line
      SERVICE_ACCOUNT_KEY_FILE_CONTENT:
        required: true
        description: The Google Service key Json File. # Note that quotation marks must be inserted with escape backslash like \" .
        # The echo command will break otherwise.
        # The \n newline characters must also be removed from the private_key value. The Action will fail otherwise.
      GH_PKG_TOKEN:
        description: A readonly Repository Key of GitHub

jobs:
  publish:
    name: Build and Publish to Google Console
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: yarn

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
      
      - name: Setup serviceAccountKey.json
        run: echo -e "${{ secrets.SERVICE_ACCOUNT_KEY_FILE_CONTENT }}" >> Service-Account-Key.json

      - name: Build and Push to Google-Console
        run: eas build --profile ${{ inputs.build-profile }} --platform ${{ inputs.platform }}  --auto-submit-with-profile ${{ inputs.auto-submit-profile }} --non-interactive ${{ inputs.build-flags }}
