name: Was last commit before N days?
on:
  workflow_call:
    inputs:
      N-Days:
        type: number
        default: 1
    outputs:
      isYoungerThanNDays:
        value: ${{ jobs.is_before_N_days.outputs.isYoungerThanNDays }}
        description: A boolean that is true, if the last commit was before input.N-Days, false otherwise


jobs:
  is_before_N_days:
    name: Evaluate if last commit was before N days
    runs-on: ubuntu-latest
    outputs:
      isYoungerThanNDays: ${{ steps.evaluate.outputs.isYoungerThanNDays }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - id: evaluate
        run: | 
          echo "Calculating if last commit was before ${{ inputs.N-Days }}
          lastCommitDateStrictISO=$(git show --no-patch --format=%cI)
          lastCommitDate=$(date --date ${lastCommitDateStrictISO} +%s)
          dateBeforeNDays=$(date --date "${{ inputs.N-Days }} days ago" +%s)
          if [ "$dateBeforeNDays" -lt "$lastCommitDate" ]
          then
            echo "Last commit was younger than ${{ inputs.N-Days }}"
            echo "isYoungerThanNDays=true" >> $GITHUB_OUTPUT
          else
            echo "Last commit was older than ${{ inputs.N-Days }}"
            echo "isYoungerThanNDays=false" >> $GITHUB_OUTPUT
          fi
          
