name: Release Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('.m2/settings.xml') }}
          restore-keys: ${{ runner.os }}-maven-
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: adopt
      - name: Copy settings.xml
        run: |
          mkdir -p ~/.m2
          cp ./.m2/settings.xml ~/.m2/
      - name: Set Git config
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
      - name: Release
        run: mvn release:prepare release:perform -B -Dartifactory.user=${{ secrets.ARTIFACTORY_USERNAME }} -Dartifactory.password=${{ secrets.ARTIFACTORY_TOKEN }} -DGITHUB_USER=${{ github.actor }} -DGITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} -Darguments="-Dmaven.repo.local=./.m2/repository -Dartifactory.user=${{ secrets.ARTIFACTORY_USERNAME }} -Dartifactory.password=${{ secrets.ARTIFACTORY_TOKEN }} -DGITHUB_USER=${{ github.actor }} -DGITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}"
