on:
  workflow_call:
    inputs:
      image-name: 
        type: string
        default: '' 
    
jobs:
  extract-effective-container-name:
    runs-on: ubuntu-latest
    outputs:
      container-name: ${{ steps.get-name.outputs.container-name }}
    steps:
      - id: get-name
        run: |
          BASE_NAME=$(basename "${{ github.repository }}")

          if [ -z "${{ inputs.image-name }}" ]; then
            CONTAINER_NAME="$BASE_NAME"
          else
            CONTAINER_NAME="$BASE_NAME/${{ inputs.image-name }}"
          fi

          echo "Effective container name: $CONTAINER_NAME"
          echo "container-name=$CONTAINER_NAME" >> $GITHUB_OUTPUT

  clean-ghcr:
    name: Delete old unused container images
    runs-on: ubuntu-latest
    needs: extract-effective-container-name
    steps:
      - name: Prune
        uses: vlaurin/action-ghcr-prune@v0.5.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          organization: ${{ github.repository_owner }}
          container: ${{ needs.extract-effective-container-name.outputs.container-name }}
          prune-untagged: true
