on: workflow_call
    
jobs:
  extract-repository-name:
    runs-on: ubuntu-latest
    outputs:
      repo-name: ${{ steps.get-repo-name.outputs.repo-name }}
    steps:
      - id: get-repo-name
        run: |
          echo "Repository owner: ${{ github.repository_owner }}"
          echo "Repository name: $(basename ${{ github.repository }})"
          echo "repo-name=$(basename ${{ github.repository }})" >> $GITHUB_OUTPUT
          
  clean-ghcr:
      name: Delete old unused container images
      runs-on: ubuntu-latest
      needs: extract-repository-name
      steps:
        - name: Prune
          uses: vlaurin/action-ghcr-prune@v0.5.0
          with:
            token: ${{ secrets.GITHUB_TOKEN }}
            organization: ${{ github.repository_owner }}
            container: ${{ needs.extract-repository-name.outputs.repo-name }}
            dry-run: true
            prune-untagged: true
