name: rollup node library
on: workflow_call

jobs:
  rollup-library:
    runs-on: ubuntu-latest
    permissions:
      packages: read
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: add verification to yarn
        run: yarn config set npmScopes.thb-it-oldenburg.npmAuthToken ${{ github.token }}

      - name: install dependencies
        run: yarn --frozen-lockfile

      - name: increase patch version
        run: yarn version patch

      - name: run rollup
        run: npx rollup -c

      - name: publish to registry configured by package.json
        run: yarn npm publish

      - name: push version chages
        uses: thb-it-oldenburg/git-push-changes-from-workflows-action@main
