name: Test and build frontend code

on:
  workflow_call:
    inputs:
      node-version:
        default: "18.x"
        type: string
      working-directory:
        default: "."
        type: string
      artifact-name:
        required: true
        type: string
      node-variables:
        type: string
    outputs:
       package-version:
        description: "Version out of package.json"
        value: ${{ jobs.test-and-build-frontend.outputs.package-version }}

env:
  REACT_APP_GHOST_API_URL: ${{ vars.REACT_APP_GHOST_API_URL }}
  REACT_APP_GHOST_API_KEY: ${{ vars.REACT_APP_GHOST_API_KEY }}

jobs:
  test-and-build-frontend:
    name: Test and build frontend Code
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    outputs:
      package-version: ${{ steps.package-version.outputs.package-version }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}
          cache: "yarn"
          cache-dependency-path: "${{ inputs.working-directory }}/yarn.lock"
          registry-url: 'https://npm.pkg.github.com'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: yarn install --frozen-lockfile --ignore-scripts

      - name: Run tests
        run: "CI='true' yarn test --passWithNoTests"

      - name: Production build
        run: "BUILD_PATH='./production/build' yarn run build"

      - name: Copy neccessary files into production folder
        run: |
          cp Dockerfile production
          cp -r docker/ production/
          
      - name: list folder
        run: ls
      
      - name: Read Version
        id: package-version
        run: |
          version=$(node -p "require('./package.json').version")
          echo "package-version=$version" >> $GITHUB_OUTPUT

      - name: Upload production artifact
        uses: actions/upload-artifact@v3.0.0
        with:
          name: "${{ inputs.artifact-name }}"
          path: "${{ inputs.working-directory }}/production/"
