name: Test and build frontend code

on:
  workflow_call:
    inputs:
      node-version:
        default: "14.x"
        type: string
      working-directory:
        default: "."
        type: string

jobs:
  test-and-build-frontend:
    name: Test And Build Frontend Code
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: $inputs:working-directory

    steps:
      - uses: actions/checkout@v2.4.0

      - name: Set up Node.js environment
        uses: actions/setup-node@v2.5.1
        with:
          node-version: $inputs:node-version
          cache: "npm"
          cache-dependency-path: "frontend/package-lock.json"

      - name: Install dependencies
        run: npm install

      - name: Run Tests
        run: "CI='true' npm test"

      - name: production build
        run: "BUILD_PATH='./production' npm run build --production"

      - name: Copy neccessary files into production folder
        run: mkdir production && cp ./{build,Dockerfile} ./production/

      - name: Upload production artifact
        uses: actions/upload-artifact@3.0.0
        with:
          name: "&{{ env.GITHUB_REPOSITORY }}-frontend"
          path: production
