### This workflow covers the complete build- and deployment-process for Maven Projects
### 1. Test and build with maven
### 2. Build a docker container image
### 3. Push the docker container image to the github registry
### 4. Trigger a webhook (if webhook-url is set)
name: Full Build- and Deployment-Process for Maven Projects

on:
  workflow_call:
    inputs:
      java-package-type:
        type: string
        default: jar
        description: Insert either 'jar' or 'war'.
      java-version:
        type: number
        default: 17
      container-tag:
        type: string
      artifact-name:
        required: true
        type: string
      webhook-url:
        type: string
        description: "if not empty, as last step this webhook url will be called"
      file-name:
        type: string
        required: false
        description: If given, creates a file to use freely in the docker build.
    secrets:
      repo-access-username:
        description: A username wich owns a repository read access token
      repo-access-token:
        description: The personal access token of the passed repo-access-username
      file-content:
        required: false
        description: Necessary if file-name is given. Must be base64 encoded.

jobs:
  use-build-backend:
    uses: thb-it-oldenburg/thb-build-actions/.github/workflows/build-java-input-command.yml@v1.3.0
    with:
      artifact-name: ${{ inputs.artifact-name }}
      artifact-path: "production"
      java-version: ${{ inputs.java-version }}
      maven-build-command: |
        mvn -B clean package --file pom.xml -U
        mkdir production
        ls
        cp target/*.${{ inputs.java-package-type }} production
        cp ./docker/Dockerfile production
    secrets:
      repo-access-username: ${{ secrets.repo-access-username }}
      repo-access-token:  ${{ secrets.repo-access-token }}

  use-build-container-push-to-registry:
    needs: [use-build-backend]
    uses: thb-it-oldenburg/thb-build-actions/.github/workflows/build-container-push-to-registry.yml@v1.5.4
    with:
      artifact-name: ${{ inputs.artifact-name }}
      container-tag: ${{ inputs.container-tag }}
      file-name: ${{ inputs.file-name }}
    secrets:
      file-content: ${{ secrets.file-content }}

  use-webhook:
    needs: [use-build-container-push-to-registry]
    runs-on: ubuntu-latest
    steps:
      - name: Call Webhook
        if: inputs.webhook-url != ''
        run: "curl -X POST ${{ inputs.webhook-url }}"

  clean-git-hub-container-registry:
      name: Remove old unused container images
      needs: use-build-container-push-to-registry
      uses: thb-it-oldenburg/thb-build-actions/.github/workflows/remove-untagged-container-images-from-calling-repo.yml@v1.2.4
