### This workflow covers the complete build- and deployment-process for Projects, wich have their complete installation defined by the 'Dockerfile' in the root of their repository
### 1. Build a docker container image
### 2. Push the docker container image to the github registry
### 3. Trigger a webhook (if webhook-url is set)
name: Full Build- and Deployment-Process for Yarn Projects

on:
  workflow_call:
    inputs:
      container-tag:
        type: string
      webhook-url:
        type: string
        description: "if not empty, as last step this webhook url will be called"
        
jobs:      
  call-docker-build:
    uses: thb-it-oldenburg/thb-build-actions/.github/workflows/build-container-push-to-registry.yml@v1.5.4
    with:
      container-tag: ${{ inputs.container-tag }}

  use-webhook:
    needs: [call-docker-build]
    runs-on: ubuntu-latest
    steps:
    - name: Call Webhook with Retry Logic
      if: inputs.webhook-url != ''
      run: |
        retries=5
        delay=10
        success=false

        for ((i=1; i<=retries; i++)); do
          echo "Attempt $i of $retries..."
          
          # Webhook-Aufruf und Statuscode speichern
          response=$(curl -s -o /dev/null -w "%{http_code}" -X POST "${{ inputs.webhook-url }}")
          echo "HTTP Response Code: $response"
          
          if [ "$response" -eq 404 ]; then
            echo "Webhook call failed with HTTP $response. Exiting..."
            exit 1
          fi

          # Erfolg, wenn der HTTP-Status 204 ist
          if [[ "$response" -ge 200 && "$response" -lt 300 ]]; then
            echo "Webhook call successful with HTTP $response!"
            success=true
            break
          else
            echo "Webhook call failed with HTTP $response. Retrying in $delay seconds..."
            sleep $delay
          fi
        done

        if [ "$success" = false ]; then
          echo "Webhook call failed after $retries attempts."
          exit 2
        fi
        
  clean-git-hub-container-registry:
      name: Remove old unused container images
      needs: call-docker-build
      uses: thb-it-oldenburg/thb-build-actions/.github/workflows/remove-untagged-container-images-from-calling-repo.yml@v1.2.4
